/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class constante {
  public static void setNum(int value) {
    constanteJNI.num_set(value);
  }

  public static int getNum() {
    return constanteJNI.num_get();
  }

}
