/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wrapper.pcl;

public class PointXYZRGBA {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public PointXYZRGBA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PointXYZRGBA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapper.pcl_moduleJNI.delete_pcl_PointXYZRGBA(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PointXYZRGBA() {
    this(wrapper.pcl_moduleJNI.new_pcl_PointXYZRGBA__SWIG_0(), true);
  }

  public PointXYZRGBA(float _x, float _y, float _z, long _rgba) {
    this(wrapper.pcl_moduleJNI.new_pcl_PointXYZRGBA__SWIG_1(_x, _y, _z, _rgba), true);
  }

  public void setX(float value) {
    wrapper.pcl_moduleJNI.pcl_PointXYZRGBA_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return wrapper.pcl_moduleJNI.pcl_PointXYZRGBA_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    wrapper.pcl_moduleJNI.pcl_PointXYZRGBA_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return wrapper.pcl_moduleJNI.pcl_PointXYZRGBA_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    wrapper.pcl_moduleJNI.pcl_PointXYZRGBA_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return wrapper.pcl_moduleJNI.pcl_PointXYZRGBA_z_get(swigCPtr, this);
  }

  public void setData(wrapper.SWIGTYPE_p_float value) {
    wrapper.pcl_moduleJNI.pcl_PointXYZRGBA_data_set(swigCPtr, this, wrapper.SWIGTYPE_p_float.getCPtr(value));
  }

  public wrapper.SWIGTYPE_p_float getData() {
    long cPtr = wrapper.pcl_moduleJNI.pcl_PointXYZRGBA_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new wrapper.SWIGTYPE_p_float(cPtr, false);
  }

  public void setRgba(long value) {
    wrapper.pcl_moduleJNI.pcl_PointXYZRGBA_rgba_set(swigCPtr, this, value);
  }

  public long getRgba() {
    return wrapper.pcl_moduleJNI.pcl_PointXYZRGBA_rgba_get(swigCPtr, this);
  }

}
