/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wrapper.pcl;

public class PointCloud_PointXYZRGBA {
  private long swigCPtr;
  private boolean swigCMemOwn;

  public PointCloud_PointXYZRGBA(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PointCloud_PointXYZRGBA obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapper.pcl_moduleJNI.delete_pcl_PointCloud_PointXYZRGBA(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PointCloud_PointXYZRGBA() {
    this(wrapper.pcl_moduleJNI.new_pcl_PointCloud_PointXYZRGBA__SWIG_0(), true);
  }

  public PointCloud_PointXYZRGBA(wrapper.pcl.PointCloud_PointXYZRGBA pc) {
    this(wrapper.pcl_moduleJNI.new_pcl_PointCloud_PointXYZRGBA__SWIG_1(wrapper.pcl.PointCloud_PointXYZRGBA.getCPtr(pc), pc), true);
  }

  public PointCloud_PointXYZRGBA(wrapper.pcl.PointCloud_PointXYZRGBA pc, wrapper.vector_int indices) {
    this(wrapper.pcl_moduleJNI.new_pcl_PointCloud_PointXYZRGBA__SWIG_3(wrapper.pcl.PointCloud_PointXYZRGBA.getCPtr(pc), pc, wrapper.vector_int.getCPtr(indices), indices), true);
  }

  public PointCloud_PointXYZRGBA(long width_, long height_, wrapper.pcl.PointXYZRGBA value_) {
    this(wrapper.pcl_moduleJNI.new_pcl_PointCloud_PointXYZRGBA__SWIG_4(width_, height_, wrapper.pcl.PointXYZRGBA.getCPtr(value_), value_), true);
  }

  public PointCloud_PointXYZRGBA(long width_, long height_) {
    this(wrapper.pcl_moduleJNI.new_pcl_PointCloud_PointXYZRGBA__SWIG_5(width_, height_), true);
  }

  public wrapper.pcl.PointCloud_PointXYZRGBA Add_To_Self(wrapper.pcl.PointCloud_PointXYZRGBA rhs) {
    return new wrapper.pcl.PointCloud_PointXYZRGBA(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_Add_To_Self(swigCPtr, this, wrapper.pcl.PointCloud_PointXYZRGBA.getCPtr(rhs), rhs), true);
  }

  public wrapper.pcl.PointCloud_PointXYZRGBA Add(wrapper.pcl.PointCloud_PointXYZRGBA rhs) {
    return new wrapper.pcl.PointCloud_PointXYZRGBA(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_Add(swigCPtr, this, wrapper.pcl.PointCloud_PointXYZRGBA.getCPtr(rhs), rhs), true);
  }

  public wrapper.pcl.PointXYZRGBA at(int column, int row) {
    return new wrapper.pcl.PointXYZRGBA(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_at__SWIG_0(swigCPtr, this, column, row), false);
  }

  public wrapper.pcl.PointXYZRGBA at(long column, long row) {
    return new wrapper.pcl.PointXYZRGBA(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_at__SWIG_2(swigCPtr, this, column, row), false);
  }

  public boolean isOrganized() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_isOrganized(swigCPtr, this);
  }

  public wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator begin() {
    return new wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_begin__SWIG_0(swigCPtr, this), true);
  }

  public wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator end() {
    return new wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_end__SWIG_0(swigCPtr, this), true);
  }

  public long size() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_size(swigCPtr, this);
  }

  public void reserve(long n) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_empty(swigCPtr, this);
  }

  public void resize(long n) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_resize(swigCPtr, this, n);
  }

  public wrapper.pcl.PointXYZRGBA at(long n) {
    return new wrapper.pcl.PointXYZRGBA(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_at__SWIG_4(swigCPtr, this, n), false);
  }

  public wrapper.pcl.PointXYZRGBA front() {
    return new wrapper.pcl.PointXYZRGBA(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_front__SWIG_0(swigCPtr, this), false);
  }

  public wrapper.pcl.PointXYZRGBA back() {
    return new wrapper.pcl.PointXYZRGBA(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_back__SWIG_0(swigCPtr, this), false);
  }

  public void push_back(wrapper.pcl.PointXYZRGBA pt) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_push_back(swigCPtr, this, wrapper.pcl.PointXYZRGBA.getCPtr(pt), pt);
  }

  public wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator insert(wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator position, wrapper.pcl.PointXYZRGBA pt) {
    return new wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_insert__SWIG_0(swigCPtr, this, wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator.getCPtr(position), wrapper.pcl.PointXYZRGBA.getCPtr(pt), pt), true);
  }

  public void insert(wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator position, long n, wrapper.pcl.PointXYZRGBA pt) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_insert__SWIG_1(swigCPtr, this, wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator.getCPtr(position), n, wrapper.pcl.PointXYZRGBA.getCPtr(pt), pt);
  }

  public wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator erase(wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator position) {
    return new wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_erase__SWIG_0(swigCPtr, this, wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator.getCPtr(position)), true);
  }

  public wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator erase(wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator first, wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator last) {
    return new wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_erase__SWIG_1(swigCPtr, this, wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator.getCPtr(first), wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator.getCPtr(last)), true);
  }

  public void swap(wrapper.pcl.PointCloud_PointXYZRGBA rhs) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_swap(swigCPtr, this, wrapper.pcl.PointCloud_PointXYZRGBA.getCPtr(rhs), rhs);
  }

  public void clear() {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_clear(swigCPtr, this);
  }

  public wrapper.pcl.PointCloud_PointXYZRGBA makeShared() {
    long cPtr = wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_makeShared(swigCPtr, this);
    return (cPtr == 0) ? null : new wrapper.pcl.PointCloud_PointXYZRGBA(cPtr, true);
  }

  public void setHeader(wrapper.SWIGTYPE_p_pcl__PCLHeader value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_header_set(swigCPtr, this, wrapper.SWIGTYPE_p_pcl__PCLHeader.getCPtr(value));
  }

  public wrapper.SWIGTYPE_p_pcl__PCLHeader getHeader() {
    return new wrapper.SWIGTYPE_p_pcl__PCLHeader(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_header_get(swigCPtr, this), true);
  }

  public void setPoints(wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_points_set(swigCPtr, this, wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t.getCPtr(value));
  }

  public wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t getPoints() {
    long cPtr = wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_points_get(swigCPtr, this);
    return (cPtr == 0) ? null : new wrapper.SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t(cPtr, false);
  }

  public void setWidth(long value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_width_set(swigCPtr, this, value);
  }

  public long getWidth() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_width_get(swigCPtr, this);
  }

  public void setHeight(long value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_height_set(swigCPtr, this, value);
  }

  public long getHeight() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_height_get(swigCPtr, this);
  }

  public void setIs_dense(boolean value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_is_dense_set(swigCPtr, this, value);
  }

  public boolean getIs_dense() {
    return wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_is_dense_get(swigCPtr, this);
  }

  public void setSensor_origin_(wrapper.SWIGTYPE_p_Eigen__Vector4f value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_sensor_origin__set(swigCPtr, this, wrapper.SWIGTYPE_p_Eigen__Vector4f.getCPtr(value));
  }

  public wrapper.SWIGTYPE_p_Eigen__Vector4f getSensor_origin_() {
    return new wrapper.SWIGTYPE_p_Eigen__Vector4f(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_sensor_origin__get(swigCPtr, this), true);
  }

  public void setSensor_orientation_(wrapper.SWIGTYPE_p_Eigen__Quaternionf value) {
    wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_sensor_orientation__set(swigCPtr, this, wrapper.SWIGTYPE_p_Eigen__Quaternionf.getCPtr(value));
  }

  public wrapper.SWIGTYPE_p_Eigen__Quaternionf getSensor_orientation_() {
    return new wrapper.SWIGTYPE_p_Eigen__Quaternionf(wrapper.pcl_moduleJNI.pcl_PointCloud_PointXYZRGBA_sensor_orientation__get(swigCPtr, this), true);
  }

}
