/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig;

public class mathJNI {
  public final static native double cos(double jarg1);
  public final static native double sin(double jarg1);
  public final static native double tan(double jarg1);
  public final static native double acos(double jarg1);
  public final static native double asin(double jarg1);
  public final static native double atan(double jarg1);
  public final static native double atan2(double jarg1, double jarg2);
  public final static native double cosh(double jarg1);
  public final static native double sinh(double jarg1);
  public final static native double tanh(double jarg1);
  public final static native double exp(double jarg1);
  public final static native double log(double jarg1);
  public final static native double log10(double jarg1);
  public final static native double pow(double jarg1, double jarg2);
  public final static native double sqrt(double jarg1);
  public final static native double fabs(double jarg1);
  public final static native double ceil(double jarg1);
  public final static native double floor(double jarg1);
  public final static native double fmod(double jarg1, double jarg2);
  public final static native double M_E_get();
  public final static native double M_LOG2E_get();
  public final static native double M_LOG10E_get();
  public final static native double M_LN2_get();
  public final static native double M_LN10_get();
  public final static native double M_PI_get();
  public final static native double M_PI_2_get();
  public final static native double M_PI_4_get();
  public final static native double M_1_PI_get();
  public final static native double M_2_PI_get();
  public final static native double M_2_SQRTPI_get();
  public final static native double M_SQRT2_get();
  public final static native double M_SQRT1_2_get();
}
