/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig;

public class math implements mathConstants {
  public static double cos(double x) {
    return mathJNI.cos(x);
  }

  public static double sin(double x) {
    return mathJNI.sin(x);
  }

  public static double tan(double x) {
    return mathJNI.tan(x);
  }

  public static double acos(double x) {
    return mathJNI.acos(x);
  }

  public static double asin(double x) {
    return mathJNI.asin(x);
  }

  public static double atan(double x) {
    return mathJNI.atan(x);
  }

  public static double atan2(double y, double x) {
    return mathJNI.atan2(y, x);
  }

  public static double cosh(double x) {
    return mathJNI.cosh(x);
  }

  public static double sinh(double x) {
    return mathJNI.sinh(x);
  }

  public static double tanh(double x) {
    return mathJNI.tanh(x);
  }

  public static double exp(double x) {
    return mathJNI.exp(x);
  }

  public static double log(double x) {
    return mathJNI.log(x);
  }

  public static double log10(double x) {
    return mathJNI.log10(x);
  }

  public static double pow(double x, double y) {
    return mathJNI.pow(x, y);
  }

  public static double sqrt(double x) {
    return mathJNI.sqrt(x);
  }

  public static double fabs(double x) {
    return mathJNI.fabs(x);
  }

  public static double ceil(double x) {
    return mathJNI.ceil(x);
  }

  public static double floor(double x) {
    return mathJNI.floor(x);
  }

  public static double fmod(double x, double y) {
    return mathJNI.fmod(x, y);
  }

}
