/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package variables;

public class variables_globales {
  public static void setProfundidad(int value) {
    variables_globalesJNI.profundidad_set(value);
  }

  public static int getProfundidad() {
    return variables_globalesJNI.profundidad_get();
  }

  public static void setDensidad(double value) {
    variables_globalesJNI.densidad_set(value);
  }

  public static double getDensidad() {
    return variables_globalesJNI.densidad_get();
  }

}
