/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package variables;

public class variables_globalesJNI {
  public final static native void profundidad_set(int jarg1);
  public final static native int profundidad_get();
  public final static native void densidad_set(double jarg1);
  public final static native double densidad_get();
}
