/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wrapper;

public class SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator {
  private long swigCPtr;

  public SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  public SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_p_std__vectorT_pcl__PointXYZRGBA_Eigen__aligned_allocatorT_pcl__PointXYZRGBA_t_t__iterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

