/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package funciones;

public class funciones {
  public static int suma(int n1, int n2) {
    return funcionesJNI.suma(n1, n2);
  }

  public static int resta(int n1, int n2) {
    return funcionesJNI.resta(n1, n2);
  }

}
