/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package funciones;

public class funcionesJNI {
  public final static native int suma(int jarg1, int jarg2);
  public final static native int resta(int jarg1, int jarg2);
}
