/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface mathConstants {
  public final static double M_E = mathJNI.M_E_get();
  public final static double M_LOG2E = mathJNI.M_LOG2E_get();
  public final static double M_LOG10E = mathJNI.M_LOG10E_get();
  public final static double M_LN2 = mathJNI.M_LN2_get();
  public final static double M_LN10 = mathJNI.M_LN10_get();
  public final static double M_PI = mathJNI.M_PI_get();
  public final static double M_PI_2 = mathJNI.M_PI_2_get();
  public final static double M_PI_4 = mathJNI.M_PI_4_get();
  public final static double M_1_PI = mathJNI.M_1_PI_get();
  public final static double M_2_PI = mathJNI.M_2_PI_get();
  public final static double M_2_SQRTPI = mathJNI.M_2_SQRTPI_get();
  public final static double M_SQRT2 = mathJNI.M_SQRT2_get();
  public final static double M_SQRT1_2 = mathJNI.M_SQRT1_2_get();
}
